name: Sync

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 */1 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get Upstream github actor
        run: |
          github_actor=$(echo ${{ secrets.UPSTREAM_SOURCE }} | cut -d/ -f1)
          echo '::set-env name=UPSTREAM_GITHUB_ACTOR::$github_actor'
      - name: Set up auth
        run: |
          git config --global http.https://github.com/.extraheader "Authorization: Basic $(echo -n "${UPSTREAM_GITHUB_ACTOR}:${{ secrets.UPSTREAM_PAT }}" | base64 --wrap=0)"
      - name: Checkout source
        run: |
          git version
          git clone -b master --depth 1 https://github.com/${{ secrets.UPSTREAM_SOURCE }} $GITHUB_WORKSPACE
          git config --local gc.auto 0
      - name: Checkout submodules
        run: |
          git submodule sync --recursive
          &>/dev/null git -c protocol.version=2 submodule update --init --force --depth=1 --recursive
      - name: Removing auth
        run: |
          git config --global --unset-all 'http.https://github.com/.extraheader'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          &>/dev/null pip install -r requirements.txt
      - name: Sync
        env:
          UPSTREAM_PAT: ${{ secrets.UPSTREAM_PAT }}
          SERVICE_TOKEN: ${{ secrets.SERVICE_TOKEN }}
        run: |
          &>/dev/null python ${{ secrets.UPSTREAM_ENTRYPOINT }}
      - name: Commit files
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Bot of emuibot"
          git add data/
          &>/dev/null git commit -m "Sync: $(date +%d.%m.%Y)" && echo "::set-output name=committed::1" || echo "Nothing to update"
      - name: Push changes
        run: |
          git push "https://${UPSTREAM_GITHUB_ACTOR}:${{ secrets.UPSTREAM_PAT }}@github.com/${{ secrets.UPSTREAM_SOURCE }}.git" HEAD:master
